name: Dynamic README (Day/Night)

on:
  schedule:
    - cron: "0 * * * *"   # Her saat başı (UTC). İçeride TZ=Europe/Istanbul kullanıyoruz.
  workflow_dispatch: {}    # Elle tetikleme

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update README dynamic block
        env:
          TZ: Europe/Istanbul
        run: |
          bash scripts/update_readme.sh

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add README.md
            git commit -m "chore(readme): dynamic day/night update [skip ci]"
            git push
          else
            echo "No changes."
          fi
